case class zip(RecordNumber : Int,
               Zipcode: Int,
               ZipCodeType:String,
               City: String,
               State: String,
               LocationType: String,
               Lat: Double,
               Long: Double,
               Xaxis: Double,
               Yaxis: Double,
               Zaxis: Double,
               WorldRegion: String,
               Country: String,
               LocationText: String,
               Location: String,
               Decommisioned: Boolean,
               TaxReturnsFiled: Int,
               EstimatedPopulation: Int,
               TotalWages: Int,
               Notes: String
              )
